### ISSUE TITLE
Update tfile.me plugin

### ISSUE THREAD

**Issue by ngosang** [danerde/qbittorrent-plugins#1]
@danerde  the tfile.me plugin is outdated. Could you fix it?

 These plugins are compatible with Python2 and Python3, you can see how they work:
- https://raw.githubusercontent.com/MrNeon/qbittorrent-search-plugins/master/strikesearch.py
- https://raw.githubusercontent.com/ngosang/qBittorrent-plugins/master/tntvillage.py

After any changes update:
https://github.com/qbittorrent/qBittorrent/wiki/Unofficial-search-plugins

**Comment by Pireo** [comment]
It has been updated, you can close.
